server:
  port: 8080
  ip: localhost
  
db:
  auth:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/get_better_tool?autoReconnect=true
    username: root
    password: password
    initial_connections: 2
    max_active_connections: 5
    min_idle_connections: 2
    max_idle_connections: 10
    max_waiting_time: 10000
    validation-query: SELECT 1
    validation-query-timeout: 30000
